// User Events
export const USER_CONNECTED = "USER_CONNECTED";
export const USER_DISCONNECTED = "USER_DISCONNECTED";

// Chat Events
export const CHAT_MESSAGE_SENT = "CHAT_MESSAGE_SENT";
export const CHAT_NOTIFICATION_SENT = "CHAT_NOTIFICATION_SENT";
export const CHAT_NOTIFICATION_RECEIVED = "CHAT_NOTIFICATION_RECEIVED";
export const CHAT_ROOM_JOINED = "CHAT_ROOM_JOINED";
export const CHAT_ROOM_LEFT = "CHAT_ROOM_LEFT";

export const CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED";
export const CHAT_MESSAGE_DELETED = "CHAT_MESSAGE_DELETED";
export const CHAT_MESSAGE_EDITED = "CHAT_MESSAGE_EDITED";
export const CHAT_ROOM_CREATED = "CHAT_ROOM_CREATED";
export const CHAT_ROOM_DELETED = "CHAT_ROOM_DELETED";
export const CHAT_NOTIFICATION_READ = "CHAT_NOTIFICATION_READ";
export const CHAT_NOTIFICATION_ACKNOWLEDGED = "CHAT_NOTIFICATION_ACKNOWLEDGED";
export const CHAT_TYPING_STARTED = "CHAT_TYPING_STARTED";
export const CHAT_TYPING_STOPPED = "CHAT_TYPING_STOPPED";
export const CHAT_TYPING_INDICATOR = "CHAT_TYPING_INDICATOR";
export const CHAT_STATUS_UPDATED = "CHAT_STATUS_UPDATED";
export const CHAT_ATTACHMENT_UPLOADED = "CHAT_ATTACHMENT_UPLOADED";

export const CALL_ACCEPT = "CALL_ACCEPT";
export const CALL_REJECT = "CALL_REJECT";
export const CALL_RECEIVE = "CALL_RECEIVE";
export const CHAT_ENDED = "CHAT_ENDED";
