// User Events
export const USER_CONNECTED = "USER_CONNECTED";
export const USER_DISCONNECTED = "USER_DISCONNECTED";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_SESSION_EXPIRED = "USER_SESSION_EXPIRED";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAILURE = "USER_AUTH_FAILURE";
export const USER_TOKEN_EXPIRED = "USER_TOKEN_EXPIRED";
export const USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED";
export const USER_PROFILE_VIEWED = "USER_PROFILE_VIEWED";
export const USER_DETAILS_CHANGED = "USER_DETAILS_CHANGED";
export const USER_ROLE_UPDATED = "USER_ROLE_UPDATED";

// Chat Events
export const CHAT_MESSAGE_SENT = "CHAT_MESSAGE_SENT";
export const CHAT_NOTIFICATION_SENT = "CHAT_NOTIFICATION_SENT";
export const CHAT_NOTIFICATION_RECEIVED = "CHAT_NOTIFICATION_RECEIVED";
export const CHAT_ROOM_JOINED = "CHAT_ROOM_JOINED";
export const CHAT_ROOM_LEFT = "CHAT_ROOM_LEFT";

export const CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED";
export const CHAT_MESSAGE_DELETED = "CHAT_MESSAGE_DELETED";
export const CHAT_MESSAGE_EDITED = "CHAT_MESSAGE_EDITED";
export const CHAT_ROOM_CREATED = "CHAT_ROOM_CREATED";
export const CHAT_ROOM_DELETED = "CHAT_ROOM_DELETED";
export const CHAT_NOTIFICATION_READ = "CHAT_NOTIFICATION_READ";
export const CHAT_NOTIFICATION_ACKNOWLEDGED = "CHAT_NOTIFICATION_ACKNOWLEDGED";
export const CHAT_TYPING_STARTED = "CHAT_TYPING_STARTED";
export const CHAT_TYPING_STOPPED = "CHAT_TYPING_STOPPED";
export const CHAT_TYPING_INDICATOR = "CHAT_TYPING_INDICATOR";
export const CHAT_STATUS_UPDATED = "CHAT_STATUS_UPDATED";
export const CHAT_HISTORY_FETCHED = "CHAT_HISTORY_FETCHED";
export const CHAT_ATTACHMENT_UPLOADED = "CHAT_ATTACHMENT_UPLOADED";
