import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/redux/Providers";
import { SocketProvider } from "@/context/Socket";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MeetSpace",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SocketProvider>
          <Providers>{children}</Providers>
        </SocketProvider>
      </body>
    </html>
  );
}
