import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";

import "./globals.css";
import { SocketProvider } from "@/context/Socket";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MeetSpace",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  const wsBaseUrl = process.env.NEXT_PUBLIC_WS_API_BASE_URL;
  return (
    <html lang="en">
      <body className={inter.className}>
        <SocketProvider url={wsBaseUrl}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <GoogleOAuthProvider clientId="987941566886-flhamhfbrti96nhqcml54l4tkod3j1as.apps.googleusercontent.com">
              {children}
            </GoogleOAuthProvider>
          </ThemeProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
